task:
  name: KayaVel
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:64,${...num_envs}}
    envSpacing: 16
    resetDist: 3.0
    maxEffort: 400.0
    clipActions: 1.0
    controlFrequencyInv: 1
    obstacles: None
  sim:
    dt: 0.025
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    add_ground_plane: true
    add_distant_light: false
    use_flatcache: true
    enable_scene_query_support: true
    disable_contact_processing: false
    enable_cameras: false
    default_physics_material:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
    physx:
      worker_thread_count: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${eq:${....sim_device},"gpu"}
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 0
      contact_offset: 0.02
      rest_offset: 0.001
      bounce_threshold_velocity: 0.2
      friction_offset_threshold: 0.04
      friction_correlation_distance: 0.025
      enable_sleeping: true
      enable_stabilization: true
      max_depenetration_velocity: 100.0
      gpu_max_rigid_contact_count: 524288
      gpu_max_rigid_patch_count: 81920
      gpu_found_lost_pairs_capacity: 1024
      gpu_found_lost_aggregate_pairs_capacity: 262144
      gpu_total_aggregate_pairs_capacity: 1024
      gpu_max_soft_body_contacts: 1048576
      gpu_max_particle_contacts: 1048576
      gpu_heap_capacity: 67108864
      gpu_temp_buffer_capacity: 16777216
      gpu_max_num_partitions: 8
    Kaya:
      collision_model:
        length: 0.1
        width: 0.8
        d_crit: 0.2
      lidar_min_step: 10
      action_smoothness: true
      update_des_velocity_automatic: true
      max_lin_vel: 1.0
      max_ang_vel: 1.0
  domain_randomization:
    randomize: true
    randomization_params:
      observations:
        on_reset:
          operation: additive
          distribution: gaussian
          distribution_parameters:
          - 0
          - 0.2
      actions:
        on_reset:
          operation: additive
          distribution: gaussian
          distribution_parameters:
          - 0
          - 0.05
      articulation_views:
        jetbot_view:
          position:
            on_reset:
              operation: direct
              distribution: uniform
              distribution_parameters:
              - - -2
                - -2
                - 0
              - - 2
                - 2
                - 0
  reward:
    r_col: -100
    r_crit: -10
    r_c: -2
    d_1: 0.2
    r_a: 0.5
    lambda: -0.5
    h_w: 0.2
    h_threashold: 0.2
    a_s: -0.02
    target_margin: 0.25
  curriculum:
    obs_after_epochs: 50
    no_Obs: 0.3
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 64
        - 64
        activation: elu
        initializer:
          name: default
        regularizer:
          name: None
      rnn:
        name: lstm
        units: 128
        layers: 1
        before_mlp: true
        concat_input: true
        layer_norm: false
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:KayaVel,${....experiment}}
      full_experiment_name: ${.name}
      device: ${....rl_device}
      device_name: ${....rl_device}
      env_name: rlgpu
      multi_gpu: ${....multi_gpu}
      ppo: true
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.1
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0005
      lr_schedule: adaptive
      kl_threshold: 0.008
      score_to_win: 20000
      max_epochs: ${resolve_default:500,${....max_iterations}}
      save_best_after: 30
      save_frequency: 25
      grad_norm: 1.0
      entropy_coef: 0.01
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 128
      minibatch_size: 4096
      mini_epochs: 4
      critic_coef: 4
      clip_value: true
      seq_length: 4
      bounds_loss_coef: 0.0001
task_name: ${task.name}
experiment: KayaVel_Box_Cyl_NoObs_500_LSTM
num_envs: 3
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: cpu
sim_device: gpu
device_id: 0
rl_device: cuda:0
multi_gpu: false
num_threads: 4
solver_type: 1
test: true
checkpoint: /home/scai/dev/oige22/omniisaacgymenvs/runs/KayaVel_Box_Cyl_NoObs_500_LSTM/nn/last_KayaVel_Box_Cyl_NoObs_500_LSTM_ep_500_rew_943.9464.pth
headless: false
enable_livestream: false
mt_timeout: 30
wandb_activate: true
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: omniisaacgymenvs
